services:
  app:
    container_name: eat_it_app
    build: .
    stdin_open: true
    environment:
      - TERM=xterm-256color
    ports:
      - 3000:3000
      - 3010:3010
      - 5555:5555
    volumes:
      - .:/app

  postgres:
    container_name: eat_it_postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=""
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  minio:
    container_name: eat_it_minio
    image: minio/minio:RELEASE.2023-11-20T22-40-07Z
    restart: always
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: my_mega_secret_password
    volumes:
      - minio:/data

  mailpit:
    container_name: eat_it_mailpit
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres:
  minio:
